version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/app/config.yml
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python mastoboost/cli.py"